#server:
#  port: 8082
#spring:
#  config:
#    import: optional:configserver:http://localhost:8012
#  application:
#    name: api-gateway
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  cloud:
#    config:
#      name: config-server
#    gateway:
#      routes:
#       - id: users-ws-status-check
#         uri: lb://users-ws
#         predicates:
#           - Path=/users-ws/users/status/check
#           - Method=GET
#           - Header=Authorization, Bearer (.*)
#         filters:
#           - RemoveRequestHeader=Cookie
#           - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
#           - AuthorizationHeaderFilter
#       - id: users-ws
#         uri: lb://users-ws
#         predicates:
#           - Path=/users-ws/users
#           - Method=POST
#         filters:
#           - RemoveRequestHeader=Cookie
#           - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
#       - id: users-ws-h2-console
#         uri: lb://users-ws
#         predicates:
#           - Path=/users-ws/h2-console
#           - Method=GET
#         filters:
#           - RemoveRequestHeader=Cookie
#           - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
#       - id: users-ws-login
#         uri: lb://users-ws
#         predicates:
#           - Path=/users-ws/users/login
#           - Method=POST
#         filters:
#           - RemoveRequestHeader=Cookie
#           - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka