spring:
  application:
    name: config-server
  profiles:
    active: git
  rabbitmq:
         host: localhost
         port: 5672
         username: guest
         password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/projects/
        git:
         uri: git@github.com:SamEkb/PhotoAppConfiguration
         passphrase: password
         clone-on-start: true
         default-label: main
         ignore-local-ssh-settings: true
         private-key: |
                -----BEGIN RSA PRIVATE KEY-----
                Proc-Type: 4,ENCRYPTED
                DEK-Info: DES-EDE3-CBC,C7B0415FC8D8FA8E

                -----END RSA PRIVATE KEY-----
server:
  port: 8012
management:
       endpoints:
              web:
                     exposure:
                            include: bus-refresh
