spring:
  application:
    name: config-server
  profiles:
    active: git
  rabbitmq:
         host: localhost
         port: 5672
         username: guest
         password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/projects/
        git:
         uri: git@github.com:SamEkb/PhotoAppConfiguration
         passphrase: password
         clone-on-start: true
         default-label: main
         ignore-local-ssh-settings: true
         private-key: |
                -----BEGIN RSA PRIVATE KEY-----
                Proc-Type: 4,ENCRYPTED
                DEK-Info: DES-EDE3-CBC,C7B0415FC8D8FA8E
                sfonSETss41Uiiod8ee8rWpNohW0nDmG7yTT2vXB0Gh6ah9ExsUDoiAbvHWN9BQt
                4HIr5/jM4qbds4l6v5qORx3Cm6JgPBsutTtAZmQPD/YEAR20OfjCXMSAo9H0rdkJ
                nxUqLabCXn604oPEVtpDBBkxFX3PTthzMq3r8uwT8VOq8jDckgMsZmAlwZIjYW2F
                o2dX7V67WPoElWSS48P7dy/G8TRUzMNB/48DEf2MHJwCdWIoNivXkzYQBHOCkeTi
                jU3Ekmz/hyyGCllrvFULIf0WX8izsTlCBAQoh08HxnfXkydpps6SURNbq+iaCY3B
                64PimvQpQybARQrXBr6of9nZxRH1Ue3RgYrOIY1hwY0FHxUyz09OFEUFZH8yfV/z
                1ggsuEf+jRsQL2t2jLXrzVu8L3pEtN22JzYWYYMSGfx4PX6ec0Lk3t9LZbgggC7y
                QPsRPgfOBJbdy94kLhyR7KEh1RC4Z5BYDe4N4aNzi4s5Z3mMW30ms9YQToI9mm41
                oC+jj0Veyye9dVbmSs//3U3cHKtcwEw72gse2MNZmW7vDffu7Uzk6sUQ7YzKShZi
                LgXcI4hN5JA9PpfkFkBnPuNZbGvT02193/UUqOeRuDmD+XmRGrDHASr5cweYyA0n
                HeuhL7GBtGc74NfO+sB+R/0SECjtKTPHPFgFIKeFR+o4KoQOy7ygk8L6hbTu2ZDJ
                Jktst8xwopUvHDY5laS34IJFGZkbgKMzgtwTEfPpuNMEyMpYny1HehcsKLHPWfmY
                XKCFJhe/yfhujE8KMQoyIqGRWsNVk9lOxumTvJUm12s16x1Rs+HWmtYUY3f7AZM6
                YhiUgDj81YvM0FHEdvKkGm7LZp261HwctLpsQkIWcgaZQzJLCVsF4ywa8+hIhXDZ
                v11h7+4+jk8kLWK3o7omjUvjK/+WJbnhc2YFaXBQcCDsEyYG2N360rTQyR+Aeb7n
                ssiWxsPs0OIeosJDp350LG4S6l06ERULW/iDn8ZtNuZlRIZ2W4AG4PRYfVRA2fOQ
                MWj56BjJlJeEhY4BIe8jnytIeImGslenI8XvYEmoT9GCYZFNBgHWrclFr0sc+/1n
                hYpDdTKC6fibVVURhV7LMsUewSQsw5OKeYhS6FMiHo+2wIRJg3ySpatREXAivGEP
                vDCJNdEczzx99EbXbHIinOk2vhReIGxU9JfSUA8l+U50usNLx8CSBqtGzf/nGShp
                aSVrbUqfBn+TRlugI4/5JTbDUVzr4cim66cwtHd7+oK87X2Y5CNnGkBYDJhTmUM3
                HLW4IjB8SVX0FFWOLVZmN0kc7Rd5Y82z9hpphWSyiGXastgotwzfJCpJt4vwrsUq
                zU8tJGWvBhOMUUx9NaotXLR4UfkGCq2bd1TMVxnuxHWbYrlpelcRHxzWsWFTNhcz
                LOYyV0Shec8z4UXT/89L2/Kmpi3gmFpFuXi/bHFqbWigAcE9b+fDxeRFI9/HRGcy
                NRute43ED2lagidH/E9BO+CY0hWCSuZdQpiPXbioPzYiCE/vAyCU07xRZRcMe9RJ
                bk+M0bCA3ZADdlcFMx62uk8jHaELv1EPVVy1KJunf6nGT6zcwCiaWj98fqEFXJ6R
                I071kScDZuw0oQRr0wZvqg7p/fzpSv8OC9ySP2DzaKPIVYD2voOKsAleh3tJ/uch
                IxVBcWee0Fn+ZNgFqrUTVjze1TmqnkBVrXdZgCK8BYei6R5XB+Ve16/xIT3MVwls
                kDE+PyXNdLrtP3oM7vXuBhTJ3t5THgA5AIsKSn1jyFWIZLE9gLku2SIcn21MNpxk
                p198Y3WdIbKI4a9aHCk9BtSmJi5a/hyD5dI3SVJqsD+s0L5/zrBj9nxb3Cpl689X
                hPqO6y6GlPlENR4BdcgpiosWSp6BojoGNkYhFnzjgFv3FrCi0idqx7TiEWspsgym
                M2FbEzCyWZ/RBuiN3eAzpIQqw6HomXb8XKENSjg1SdH81/YEarL2PFvAnBDNnqw1
                KBK3y+5x64pEr/YL9emb5gB6zKlVCqWo0P5Aq+RHdTsURsRj8CpaOd8u4ozTX6xW
                scqdNsxQXTtXLBvOkfRXQUELD2YflqdR2FUNAy8/8Kf56axRSRRSZnlHV1jaF/PS
                dt9VusTemqpexuKhCaTRPzyNDbq1XoGZ4V9PkZQ6HZTk4vqGj3fznYxTQNbBYjj5
                JYVmAADKLgnayfFiog5fXH8C5PmAKCMMgNeV9odfqLejUvpqrYVs+TcH5LWtmhrx
                4TXT0ElpiEwQt2SRiUKzFKuunIJIGx3+3pXfyo5kdFcunzIOO9v/p76nK1ui6+Qm
                D1ondwFXfHwTgyhKoct6bJtfxAiMitm4QYJtKZn8j5Glno+JrVfHsVBKRqYIiM6U
                kv2X9unYUPtrt/+uIMBvxGpKCV13eFGrXlP2d+O0CQl3dw9UaJjsHfo0Y0mijf7s
                ylw5lOvgdPx4R5uVKmpmYtsTWIOQkO3EKfjekZ74Sz0vbgLk8AEOIj/2tATV7/Zw
                TOc8lJfl6CHjSzgd3Rz3/xFJwEC+Ci78d7dak1+x4Ie4unfYDAOQlwY3gvhDV8RC
                uWaSqS0/voRIJ6kS3muMV7br30YWXPawIH0OOrTKlaAslK2nPgqvejl4NUgnaMQP
                MTMppgsNhxbqNxKv50VJZj6Harn1/wthU3wnLk3S6h+8cDOyYM0UGq2gPvlx9RCN
                LbtqZkfOgB14LH+Dnn0OlTe+wN0bUPeOJ1IaxotnhQ8LFBIM+urckIhNjgIXu9Xp
                BrXXf+MLimZtNKNtZp0oJb6Lu7cg6TKvnm4fB0cy/KAs4KdUAuYvsEatOgmFYHee
                XU7b0KgbZ4nngJKyQYyL5xdND4Qij+OJPWe6kpwOLRA+aPPRy0Wpa44p68E50ZIv
                STfxrmsSyK61KYn1qMtq3tBFxvgH+IZo1ouJicwnR+eyiXbhpg3yytCuohDM74Nx
                Od1iKPWJMPv9qamCC33TAGc/2iOifCv+EKysqjsM7FWlCk3CTXM7UL8cFbd+cvvF
                qQfC9u6sAow1UllxUG2r+4ww35BdTEaRLc2FBSavnbDmQIPWgFVclyDv3mBqi86a
                Gs4nZXnb/ovt1WdycpwyTC5It6pl4xsemBiC2GGH4xUCAoZa3R7NHHojfWiAzrNa
                -----END RSA PRIVATE KEY-----
server:
  port: 8012
management:
       endpoints:
              web:
                     exposure:
                            include: bus-refresh
