server:
  port: ${PORT:0}
spring:
  config:
    import: optional:configserver:http://localhost:8012
  cloud:
    config:
      name: albums-ws
  application:
    name: albums-ws
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  file:
    name: albums-ws.log
  pattern:
    level: '%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]'