spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8012
  cloud:
    config:
      name: discovery-service
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka
server:
  port: 8010
